Repository Team18-T-World/TViewing, pull requests merged in 2023-09, with the labels that each got.

#3 [MERGE] : ✅: gitIgnore
  .gitignore
Labels: PACK

#4 프로젝트 이름 전환
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  .idea/migrations.xml
  app/build.gradle.kts
  app/src/androidTest/java/com/example/tviewing/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/tviewing/MainActivity.kt
  app/src/main/java/com/example/tviewing/home/HomeFragment.kt
  app/src/main/java/com/example/tviewing/myVideo/MyVideoFragment.kt
  app/src/main/java/com/example/tviewing/search/SearchFragment.kt
  app/src/main/java/com/example/tviewing/videoDetail/VideoDetailFragment.kt
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/test/java/com/example/tviewing/ExampleUnitTest.kt
  settings.gradle.kts
Labels: RENAME

#8 [DESIGN] UI/my page1
  .idea/gradle.xml
  app/build.gradle.kts
  app/src/main/java/com/example/tviewing/MainActivity.kt
  app/src/main/java/com/example/tviewing/myVideo/MyVideoFragment.kt
  app/src/main/res/layout/fragment_my_video.xml
  app/src/main/res/layout/fragment_my_video_item.xml
Labels: MERGE

#10 [FEAT] : ⚙️: fragment_search, search_item UI 구현
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/search_item.xml
Labels: FEAT

#14 패키지 이름 수정
  app/src/androidTest/java/com/tworld/tviewing/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/tviewing/home/HomeFragment.kt
  app/src/main/java/com/tworld/tviewing/MainActivity.kt
  app/src/main/java/com/tworld/tviewing/home/HomeFragment.kt
  app/src/main/java/com/tworld/tviewing/myVideo/MyVideoFragment.kt
  app/src/main/java/com/tworld/tviewing/search/SearchFragment.kt
  app/src/main/java/com/tworld/tviewing/videoDetail/VideoDetailFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_video_detail.xml
  app/src/test/java/com/tworld/tviewing/ExampleUnitTest.kt
Labels: RENAME

#18 [FEAT] : ⚙️: 인터넷 권한 추가 및 의존성 추가
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
Labels: FEAT
