Repository Team18-T-World/TViewing, pull requests merged in 2023-10, with the labels that each got.

#23 [FEAT] : ⚙️: SearchFragment에서 아이템 클릭시 DetailActivity로 전환기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/tworld/tviewing/MainActivity.kt
  app/src/main/java/com/tworld/tviewing/search/SearchAdaptor.kt
  app/src/main/java/com/tworld/tviewing/search/SearchFragment.kt
  app/src/main/java/com/tworld/tviewing/videoDetail/DetailActivity.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/fragment_search.xml
Labels: FEAT

#24 [FEAT] : ⚙️: SearchFragment에서 DetailActivity로 데이터 전달
  app/src/main/java/com/tworld/tviewing/search/SearchFragment.kt
Labels: FEAT

#26 메뉴 리사이클러뷰 구현
  app/src/main/java/com/tworld/tviewing/MainActivity.kt
  app/src/main/java/com/tworld/tviewing/home/HomeAdapter.kt
  app/src/main/java/com/tworld/tviewing/home/HomeFragment.kt
  app/src/main/java/com/tworld/tviewing/home/MainMenuAdapter.kt
  app/src/main/java/com/tworld/tviewing/home/MenuItem.kt
  app/src/main/java/com/tworld/tviewing/home/SubMenuAdapter.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/main_menu_item.xml
  app/src/main/res/layout/sub_menu_item.xml
Labels: FEAT, RENAME, REMOVE

#27 [FEAT] : ⚙️: MVVM 패턴으로 마이페이지 리사이클러뷰 기능 추가 #12
  app/build.gradle.kts
  app/src/main/java/com/tworld/tviewing/myVideo/MyPageAdapter.kt
  app/src/main/java/com/tworld/tviewing/myVideo/MyPageDao.kt
  app/src/main/java/com/tworld/tviewing/myVideo/MyPageDatabase.kt
  app/src/main/java/com/tworld/tviewing/myVideo/MyPageEntity.kt
  app/src/main/java/com/tworld/tviewing/myVideo/MyPageRepository.kt
  app/src/main/java/com/tworld/tviewing/myVideo/MyPageViewModel.kt
  app/src/main/java/com/tworld/tviewing/myVideo/MyVideoFragment.kt
  app/src/main/res/layout/fragment_my_video_item.xml
Labels: MERGE

#33 홈 프래그먼트에 필요한 코드 추가
  app/build.gradle.kts
  app/src/main/java/com/tworld/tviewing/home/HomeAdapter.kt
  app/src/main/java/com/tworld/tviewing/home/HomeFragment.kt
  app/src/main/java/com/tworld/tviewing/home/MainMenuAdapter.kt
  app/src/main/java/com/tworld/tviewing/home/SubMenuAdapter.kt
  app/src/main/java/com/tworld/tviewing/home/VideoItems.kt
  app/src/main/java/com/tworld/tviewing/youtube/YoutubeService.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/home_video_item.xml
  app/src/main/res/layout/main_menu_item.xml
  app/src/main/res/layout/sub_menu_item.xml
  build.gradle.kts
Labels: FEAT, REFACTOR, MERGE, DESIGN

#37 디자인 및 버그 수정 등
  app/src/main/java/com/tworld/tviewing/home/HomeAdapter.kt
  app/src/main/java/com/tworld/tviewing/myVideo/MyPageAdapter.kt
  app/src/main/java/com/tworld/tviewing/search/SearchFragment.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_video.xml
  app/src/main/res/layout/fragment_my_video_item.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_video_detail.xml
  app/src/main/res/layout/item_home.xml
  app/src/main/res/values/strings.xml
Labels: MERGE
